### PR TITLE
fix alignment issues

### PR DESCRIPTION
**Pull request by ghost**
this is it man ;)

---
This change is [Reviewable](https://reviewable.io/reviews/hugo-events/mosaico/7)

### CODE REVIEW

**Comment by bubenkoff** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/bindings/wysiwygs.js, line 239 at r1](https://reviewable.io:443/reviews/hugo-events/mosaico/7#-KVzOPsQjNeUKB14RF4w:-KVzOPsQjNeUKB14RF4x:bupcqvc) ([raw file](https://github.com/hugo-events/mosaico/blob/890d351fe8618349ab92b7682be64e76b2e57b4c/src/js/bindings/wysiwygs.js#L239)):_

> ``` JavaScript
>               format: 'raw'
>             }).trim();
>             console.log('setup:',content);
> ```

remove logging

---

_[src/js/bindings/wysiwygs.js, line 297 at r1](https://reviewable.io:443/reviews/hugo-events/mosaico/7#-KVzOT19vXfAZ5fIuDvL:-KVzOT1AUAIszqNR9ZfQ:bupcqvc) ([raw file](https://github.com/hugo-events/mosaico/blob/890d351fe8618349ab92b7682be64e76b2e57b4c/src/js/bindings/wysiwygs.js#L297)):_

> ``` JavaScript
>             });
>           } else {
>             console.log('computed:',content);
> ```

remove logging

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hugo-events/mosaico/7)_

**Comment by ghost** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/bindings/wysiwygs.js, line 239 at r1](https://reviewable.io:443/reviews/hugo-events/mosaico/7#-KVzOPsQjNeUKB14RF4w:-KVzSCHN-_rCtmWHOzPW:b-896fix) ([raw file](https://github.com/hugo-events/mosaico/blob/890d351fe8618349ab92b7682be64e76b2e57b4c/src/js/bindings/wysiwygs.js#L239)):_
<details><summary>

<i>Previously, bubenkoff (Anatoly Bubenkov) wrote…</i></summary>



> remove logging
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hugo-events/mosaico/7)_

**Comment by ghost** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/bindings/wysiwygs.js, line 297 at r1](https://reviewable.io:443/reviews/hugo-events/mosaico/7#-KVzOT19vXfAZ5fIuDvL:-KVzSOcXFzmRywShfXHc:b-896fix) ([raw file](https://github.com/hugo-events/mosaico/blob/890d351fe8618349ab92b7682be64e76b2e57b4c/src/js/bindings/wysiwygs.js#L297)):_
<details><summary>

<i>Previously, bubenkoff (Anatoly Bubenkov) wrote…</i></summary>



> remove logging
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hugo-events/mosaico/7)_

**Comment by bubenkoff** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hugo-events/mosaico/7)_

**Pull request merged**
